version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=grogstore
      - POSTGRES_USER=grogstore
      - POSTGRES_DB=grogstore
    ports:
      - 5432:5432
  
  app:
    build:
      context: "."
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/grogstore
    ports:
      - 8080:8080
    depends_on:
      - db